#! /usr/bin/env python

import sys
import subprocess

if len(sys.argv) > 1:
    cmd = sys.argv[1:-1]
    filename = sys.argv[-1]

#    if '-f' in cmd:
#        cmd[cmd.index['-f']] = '--follow_annotations'

    if '-f' in cmd:
	cmd.remove('-f')

    if '-p' in cmd:
	cmd.remove(cmd[cmd.index('-p') +1])
	cmd.remove('-p')


    mcmd = ['./mistral-fzn']
    mcmd.extend(cmd)
    mcmd.extend(['--print_sol', '-v 0', '--prefix_sol', '%', '--prefix_comment', '%', '--prefix_obj', '%', '--prefix_stat', '%', '--prefix_res', '%', '-f', filename, '-c', 'dom/wdeg', '-b', 'minval+guided', '-r', 'luby'])


    mistral = subprocess.Popen(mcmd) #, stdout=subprocess.PIPE)
    mistral.wait()
