#! /usr/bin/env python

import sys
import subprocess

if len(sys.argv) > 1:
    cmd = sys.argv[1:-1]
    filename = sys.argv[-1]

#    if '-f' in cmd:
#        cmd[cmd.index['-f']] = '--follow_annotations'

    if '-f' in cmd:
	cmd.remove('-f')

	#mcmd = ['./mistral-fzn']
    #We assume fz/ is in the $PATH
    mcmd = ['mistral-fzn']
    
    if '-p' in cmd:
	#cmd.remove(cmd[cmd.index('-p') +1])
	#cmd.remove('-p')
	#Now we support parallelization. The -p gives the number of threads 
	mcmd = ['mistral-fzn_parallel']
   

   
    mcmd.extend(cmd)
    mcmd.extend(['--print_sol', '-v 0', '-z 2', '--prefix_sol', '%', '--prefix_comment', '%', '--prefix_obj', '%', '--prefix_stat', '%', '--prefix_res', '%', '-f', filename, '-c', 'dom/gwdeg', '-b', 'adapted', '--follow_annotations', '--branch_on_aux', '--seed 26071986'])


#    for w in mcmd:
#        print w,
#    print


    mistral = subprocess.Popen(mcmd) #, stdout=subprocess.PIPE)
    mistral.wait()
